import type {Metadata} from "next";
import Script from 'next/script'
import Link from 'next/link'
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import 'bootstrap-icons/font/bootstrap-icons.css';
import {AskQuestion} from "@/app/AskQuestion";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="top">
            <div className="header">
                <div className="header__up">
                    <div className="logo">
                        <Link href="/">
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img className="main_logo" src="/img/logo.png" alt="logo"/>
                        </Link>
                    </div>
                    <div className="telegram">
                        <Link href="https://t.me/vpbust" className="link__black">
                            <i className="bi bi-telegram"></i> Написать в Телеграм
                        </Link>
                    </div>
                    <div className="mail link__black">
                        <i className="bi bi-envelope-at-fill"></i> mail@iusticia.ru
                    </div>
                    <div className="phone link__black">
                        <i className="bi bi-telephone-fill"></i> +79102210010
                    </div>
                </div>
                <div className="header__down">
                    <ul className="nav">
                        <Link href="/" className="link__white">
                            <li>Консультация Юриста</li>
                        </Link>
                        <Link href="/ranenie" className="link__white">
                            <li>Выплаты ранение</li>
                        </Link>
                        <Link href="/gibel" className="link__white">
                            <li>Выплаты гибель</li>
                        </Link>
                        <a href="#" className="link__white">
                            <li>Безвести провавший</li>
                        </a>
                        <a href="#" className="link__white">
                            <li>Отзывы</li>
                        </a>
                        <a href="#" className="link__white">
                            <li>О компании</li>
                        </a>
                    </ul>
                </div>
            </div>
            <div className="help">
                <h1 className="help__up">Консультация военного юриста</h1>
                <div className="help__down">
                    <div className="help__down__left">
                        <h2 className="help__down__left__header">Юридическая защита военнослужащих и их семей</h2>

                        <div className="p"><b>+</b> консультируют юристы, проходившие службу в органах военной юстиции</div>
                        <div className="p"><b>+</b> тщательная подготовка к консультации, углубленная работа с клиентом</div>
                        <div className="p"><b>+</b> пакетное предложение для тех, у кого часто возникают вопросы</div>
                        <div className="p"><b>+</b> низкие цены</div>
                    </div>
                    <AskQuestion/>
                </div>
            </div>
            <div className="main">
                <h2 className="main__header">С нами работают военнослужащие:</h2>
                <div className="main__list">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className="main__checklist" src="/img/mo_rf.jpg" alt="mo_rf"/>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className="main__checklist" src="/img/fsbrf.jpg" alt="fsb"/>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className="main__checklist" src="/img/sk_rf.jpg" alt="sk"/>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className="main__checklist" src="/img/mcs_rf.jpg" alt="mcs"/>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className="main__checklist" src="/img/mvd_rf.jpg" alt="mvd"/>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img className="main__checklist" src="/img/rosgv.jpg" alt="rosgv"/>
                </div>
            </div>

            {children}

            <div className="footer">
                <div className="logo">
                    <img className="main_logo" src="/img/logo.png" alt="logo"/>
                </div>
                <div className="vizitka__down">
                    <i className="bi bi-telephone-fill"></i> +79102210010 <br/>
                    <br/><br/>
                    <i className="bi bi-envelope-at-fill"></i> mail@iusticia.ru <br/>
                    <br/><br/>
                    <i className="bi bi-telegram"></i> t.me/vpbust <br/>
                    <br/><br/>
                    <Link href="/cofidential" className="link__white">Политика конфиденциальности.</Link>
                </div>
                <div className="footer__map">
                    <iframe
                        src="https://yandex.ru/map-widget/v1/?um=constructor%3Adde35808e8071b3d5af89226029951ab2d04e82afcc1688ceb6e5f75b8cfc311&amp;source=constructor"
                        width="300"
                        height="200"
                        frameBorder="0">
                    </iframe>
                </div>
            </div>
        </div>

        <Script src="https://widget.gravi.org/code/index.js" data-grv-id="1576" data-grv-key="10ot0h4nilmav52nuy"
                async/>

        </body>
        </html>
    );
}
