import type {Metadata} from "next";
import Image from "next/image";
import Script from 'next/script'
import Link from 'next/link'
import {Geist, Geist_Mono} from "next/font/google";
import logoImg from './resources/logo.png'
import logoImg2 from './resources/logo2.png'
import "./globals.scss";
import 'bootstrap-icons/font/bootstrap-icons.css';
import React from "react";
// import {AskQuestion} from "@/app/AskQuestion";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="top">
            <div className="header">
                <div className="header__up pc-container">
                    <div className="logo">
                        <Link href="/">
                            <Image className="main_logo" src={logoImg} alt="logo"/>
                        </Link>
                    </div>
                    <div className="telegram ">
                        <Link href="https://t.me/vpbust" className="link__black">
                            <i className="bi bi-telegram"></i> Написать в Телеграм
                        </Link>
                    </div>
                    <div className="mail link__black">
                        <i className="bi bi-envelope-at-fill"></i><a className="link__black" href="mailto:mail@iusticia.ru"> Напишите нам</a>
                    </div>
                    <div className="phone link__black">
                        <i className="bi bi-telephone-fill"></i><a className="link__black" href="tel:+79102210010"> +7-910-221-00-10</a>
                    </div>
                </div>
                <div className="header__down">
                    <ul className="nav pc-container">
                        <Link href="/" className="link__white">
                            <li>Консультация Юриста</li>
                        </Link>
                        <Link href="/ranenie" className="link__white">
                            <li>Выплаты ранение</li>
                        </Link>
                        <Link href="/gibel" className="link__white">
                            <li>Выплаты гибель</li>
                        </Link>
                        <Link href="#" className="link__white">
                            <li>Без вести пропавший</li>
                        </Link>
                        <a href="#" className="link__white">
                            <li>Отзывы</li>
                        </a>
                        <Link href="/about" className="link__white">
                            <li>О компании</li>
                        </Link>
                    </ul>
                </div>
            </div>

            {children}

            <div className="footer">
                <div className="footer__list pc-container">
                    <Link href="/" className="logo">
                        <Image className="main_logo" src={logoImg2} alt="logo"/>
                    </Link>
                    <div className="vizitka__down">
                        {/*<i className="bi bi-telephone-fill"></i> +79102210010 <br/>*/}
                        {/*<i className="bi bi-envelope-at-fill"></i> mail@iusticia.ru <br/>*/}
                        {/*<i className="bi bi-telegram"></i> t.me/vpbust <br/>*/}
                        <div className="telegram">
                            <Link href="https://t.me/vpbust" className="link__white">
                                <i className="bi bi-telegram"></i> Написать в Телеграм
                            </Link>
                        </div>
                        <div className="mail link__white">
                            <i className="bi bi-envelope-at-fill"></i><a className="link__white" href="mail@iusticia.ru"> Напишите нам</a>
                        </div>
                        <div className="phone link__white">
                            <i className="bi bi-telephone-fill"></i><a className="link__white" href="tel:+79102210010"> +7-910-221-00-10</a>
                        </div>
                        <Link className="link__white" href="/cofidential">Политика конфиденциальности</Link>
                    </div>
                    <div className="footer__map">
                        <iframe
                            src="https://yandex.ru/map-widget/v1/?um=constructor%3Adde35808e8071b3d5af89226029951ab2d04e82afcc1688ceb6e5f75b8cfc311&amp;source=constructor"
                            width="300"
                            height="200"
                            frameBorder="0">
                        </iframe>
                    </div>
                </div>
            </div>
        </div>

        <Script src="https://widget.gravi.org/code/index.js" data-grv-id="1576" data-grv-key="10ot0h4nilmav52nuy"
                async/>

        </body>
        </html>
    );
}
