import type {Metadata} from "next";
import Script from 'next/script'
import Link from 'next/link'
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="top">
            <div className="header">
                <div className="header__up">
                    <div className="logo">
                        <Link href="/">
                            <img src="/img/logo.png" alt="logo"/>
                        </Link>
                    </div>
                    <div className="telegram">
                        <i className="bi bi-telegram"></i> <a href="https://t.me/vpbust">Написать в Телеграм</a>
                    </div>
                    <div className="mail">
                        <i className="bi bi-envelope-at-fill"></i> mail@iusticia.ru
                    </div>
                    <div className="phone">
                        <i className="bi bi-telephone-fill"></i> +79102210010
                    </div>
                </div>
                <div className="header__down">
                    <ul className="nav">
                        <a href="#">
                            <li>Консультация Юриста</li>
                        </a>
                        <a href="#">
                            <li>Выплаты ранение</li>
                        </a>
                        <a href="#">
                            <li>Выплаты гибель</li>
                        </a>
                        <a href="#">
                            <li>Безвести провавший</li>
                        </a>
                        <a href="#">
                            <li>Отзывы</li>
                        </a>
                        <a href="#">
                            <li>О компании</li>
                        </a>
                    </ul>
                </div>
            </div>
            <div className="help">
                <h1 className="help__up">Консультация военного юриста</h1>
                <div className="help__down">
                    <div className="help__down__left">
                        <h3 className="help__down__left__header">Юридическая защита военнослужащих и их семей</h3>
                        <div className="p">+ консультируют юристы, проходившие службу в органах военной юстиции</div>
                        <div className="p">+ тщательная подготовка к консультации, углубленная работа с клиентом</div>
                        <div className="p">+ пакетное предложение для тех, у кого часто возникают вопросы</div>
                        <div className="p">+ низкие цены</div>
                    </div>
                    <div className="help__down__right">
                        <h3 className="help__down__right__header">Есть вопросы? Оставьте заявку:</h3>
                        <form className="cons__form" action="send.php" method="post">
                            <label htmlFor="phone">Введите номер телефона:</label>
                            <input type="tel" id="phone" name="phone" placeholder="+7 (___) ___-__-__" required/>
                            <button type="submit">Получить консультацию юриста</button>
                        </form>
                    </div>
                </div>
            </div>

            {children}

            <div className="footer">
                <div className="logo">
                    <img src="/img/logo.png" alt="logo"/>
                </div>
                <div className="vizitka__down">
                    <i className="bi bi-telephone-fill"></i> +79102210010 <br/>
                    <i className="bi bi-envelope-at-fill"></i> mail@iusticia.ru <br/>
                    <i className="bi bi-telegram"></i> t.me/vpbust
                </div>
                <div className="footer__map">
                    <iframe
                        src="https://yandex.ru/map-widget/v1/?um=constructor%3Adde35808e8071b3d5af89226029951ab2d04e82afcc1688ceb6e5f75b8cfc311&amp;source=constructor"
                        width="300"
                        height="200"
                        frameBorder="0">
                    </iframe>
                </div>
                <Link href="/cofidential">Политика конфиденциальности.</Link>
            </div>
        </div>

        <Script src="https://widget.gravi.org/code/index.js" data-grv-id="1576" data-grv-key="10ot0h4nilmav52nuy" async/>

        </body>
        </html>
    );
}
